### ISSUE TITLE
[9.0] Issue when deactivating a product 

### ISSUE THREAD

**Issue by RoelAdriaans** [bista-sales/sales-forecast#1]
When we try to disable a product in Odoo v9 enterprise, we get an error because the _get_domain_dates() method returns None, but odoo expects an list.

The error is here: https://github.com/bista-sales/sales-forecast/blob/9.0/sale_forecast/sale_forecast.py#L430

This super method is only called when self has one or more products, when self is an empty recordset super isn't called and the method returns None.

**Comment by bista-nimesh** [comment]
Issue  has been resolved in latest commit.

**Comment by RoelAdriaans** [comment]
:+1: 
That was quick :)
